services:
  - type: web
    name: despacho
    runtime: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
